### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by distortednet** [distortednet/TwitchDB#1]
There is a current bug in TwitchDB where memory leaks will happen over time. the bug effects the index and streams page, rendering them unusable and bringing the whole site down eventually.

The bug could be related to the chunks() function, however its more likely to be an issue with either getliveusers() or GetOnlineUsers()

the naming conventions of these functions suck, getliveusers is responsible for communicating with the Twitch API, and GetOnlineUsers() pulls all the users from the database, feeds it to getliveusers and checks who is online.

the problem is as follows:

because Twitch limits the amount of users you can send to the API to check who is online, it must be split up into multiple API calls and processed in batch. This is done with jsonraver.

How everything was initially structured, this caused a memory leak, although the leak isn't instantly obvious since the relevant routes are cached for 5 minutes after the initial request, then recached after that time is up. Each actual request adds anywhere from 1-5mb of ram usage.

I since added oboe to help cut down the size of the json response and use streaming json, and this required me to dump the response to a file which is then rendered internally in /api/streams/json

this does not appear to resolve the issue. I am not sure which function is causing it, but it might very well be a problem with jsonraver itself.

**Comment by Oyed** [comment]
Once my current PR has been dealt with I'll submit another PR normalising function names throughout TwitchDB to camel case.

I'll take a look at the memory leak; if you're storing any of the info you're getting in arrays or something, then that could contribute towards a memory leak if they get insanely large. I'll take a look at some point.
