### ISSUE TITLE
Better DB search sorting

### ISSUE THREAD

**Issue by PooPooUndees** [distortednet/TwitchDB#13]
So I've noticed that you have you DB search sorted by date however it sorts based on numerical values as opposed to actual date, meaning the newest isn't always first. The sorting filter reads each number in the date as individual digits instead of reading each part of the date as a whole number which results in it displaying the highest digit at the top of the list instead of the highest number. For example the date 9/9/2015 will be above the date 9/10/2015 because the number 9 is larger than the number 1 even though 10 is higher than 9. Just a small thing I thought I'd bring up with you so that you were aware of the newest intros having a chance of not being seen.

**Comment by distortednet** [comment]
well TIL, woops! i will get it fixed, that explains a lot. Thanks :D
