### ISSUE TITLE
Not Showing Up in Database

### ISSUE THREAD

**Issue by Raravin** [distortednet/TwitchDB#14]
http://www.twitchdb.tv/profile/u/raravin

**Comment by MellowNebula** [comment]
All entries are approved/denied manually. Your profile hasn't been approved yet.

**Comment by Raravin** [comment]
Ahh Okay since I miss read the thing my bad

**Comment by MellowNebula** [comment]
Not a problem, you should be good to go now :)

**Comment by Raravin** [comment]
Ty ty
