### ISSUE TITLE
Add Markdown to Intros

### ISSUE THREAD

**Issue by conceptionals** [distortednet/TwitchDB#15]
Would it be possible to add Markdown support to intros? I think it could make the intros look more pretty! For example if a user wants to add a link in their intro, they will just give the URL, but this would look **A LOT** better if they could just use Markdown for their link to make it *text* and not a *long and ugly* URL.

**Comment by distortednet** [comment]
SOON! there are a few ways to do this, some are complex. I would like to add in a rich text editor of some sort that supports that, but some of them are really absurdly difficult to work with D:

**Comment by conceptionals** [comment]
WHOOO \o/ 

Sounds good to me! :D
