### ISSUE TITLE
Allow search based on Twitch username

### ISSUE THREAD

**Issue by leegreaves** [distortednet/TwitchDB#31]
I notice that you have search enabled only for games only. Would it not be wise to also allow searches to be made on a twitch channels name or part of a channel name thereof, which includes the use of *wildcards* if the full name of the channel is not known.

**Comment by distortednet** [comment]
which version of twitchdb? this should be working on beta.twitchdb.tv but if not, i'll be sure to add it as a bug to fix!

**Comment by leegreaves** [comment]
I did mean on the old site ie twitchdb.tv. I didnt know you had a beta.twitchdb.tv though when I went there and logged in with my twitch account when I went into the search page I couldnt actually do a search as there was no search box visible.

**Comment by distortednet** [comment]
ah, there is but its not completely apparent (thanks material design) the search box is actually just above that single line.

i think im gonna go through and make sure all input boxes are a bit more obvious, though!

but yeah, that issue's been solved in the new version (hopefully, i will test when i get a moment!)

**Comment by leegreaves** [comment]
Well sounds like this little issue should be resolved then. Ill close this thread down and we can assume as [RESOLVED]
