### ISSUE TITLE
Add timezones

### ISSUE THREAD

**Issue by distortednet** [distortednet/TwitchDB#8]
Add in timezones to the schedule section when creating/editing an intro

**Comment by jackmawer** [comment]
I suggest you watch this first :) https://www.youtube.com/watch?v=-5wpm-gesOY

**Comment by distortednet** [comment]
have and that's why im terrified of even starting this hahahaha. that youtube channel is great :D

**Comment by jackmawer** [comment]
@distortednet Good luck then :) I agree, it's been very helpful to me.
